groups:
  - name: iot_api_alerts
    rules:
      - alert: HighErrorRate
        expr: increase(iot_api_http_requests_total{status=~"5.."}[1m]) > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High error rate on API"
          description: "More than 5 errors occurred in the last minute"
