global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'iot-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']   # Adjust host/port if running in Docker


rule_files:
  - 'alerts.yml'