scrape_configs:
  - job_name: 'api-service'
    static_configs:
      - targets: ['api:5000']  # Use Docker service name

  - job_name: 'aggregator'
    static_configs:
      - targets: ['aggregator:5000']

  - job_name: 'alerter'
    static_configs:
      - targets: ['alerter:5000']

rule_files:
  - "alert.yml"
