name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        ports: ['2181:2181']

      kafka:
        image: confluentinc/cp-kafka:7.4.0
        ports: ['9092:9092']
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      timescaledb:
        image: timescale/timescaledb:latest-pg14
        ports: ['5434:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: iot

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install deps & lint Dashboard
        working-directory: ./dashboard
        run: |
          npm ci
          # Optional: Uncomment if you have a lint script
          # npm run lint
          # Optional: Uncomment if you add dashboard tests
          # npm test

      - name: 📦 Install deps & test API
        working-directory: ./api
        run: |
          npm ci
          # Optional: Uncomment if you have lint or tests here
          # npm run lint
          # npm test

      - name: 🧪 Run root tests (e.g., aggregator utils)
        run: |
          npm ci
          npm test

      - name: 🐳 Build all Docker services
        run: |
          docker compose build --parallel
